name: currency_calc
description: Currency Calculator by github.com/tnsoftbear
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.5
  intl: any
  shared_preferences: ^2.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  country_icons: ^2.0.2
  flutter_svg: ^2.0.5
  provider: ^6.0.5
  flutter_hooks: ^0.18.6
  equatable: ^2.0.5
  # vertical_tabs_flutter: ^1.0.0
  vertical_tabs_flutter:
    git:
      url: https://github.com/tnsoftbear/vertical_tabs_flutter.git
      ref: fix_transparency

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  lints: ^2.0.1
  flutter_lints: ^2.0.1

flutter:
  generate: true # Enable generation of localized Strings from arb files.
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: IndieFlower
      fonts:
        - asset: fonts/IndieFlower-Regular.ttf
    - family: MaterialIcons
      fonts:
        - asset: fonts/MaterialIcons-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
