name: currency_calc
description: Currency Calculator by github.com/tnsoftbear
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  shared_preferences: ^2.3.0
  hive_flutter: ^1.1.0
  flutter_svg: ^2.0.10+1
  provider: ^6.1.2
  equatable: ^2.0.5
  # vertical_tabs_flutter: ^1.0.0
  vertical_tabs_flutter:
    git:
      url: https://github.com/tnsoftbear/vertical_tabs_flutter.git
      ref: fix_transparency
  clock: ^1.1.1
  dio: ^5.6.0
  flutter_native_splash: ^2.4.1
  mockito: ^5.4.4
  flutter_hooks: ^0.20.5
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.12
  lints: ^4.0.0
  flutter_lints: ^4.0.0

flutter:
  generate: true # Enable generation of localized Strings from arb files.
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: IndieFlower
      fonts:
        - asset: fonts/IndieFlower-Regular.ttf
    - family: MaterialIcons
      fonts:
        - asset: fonts/MaterialIcons-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf

# Don't forget to run on changes: dart run flutter_native_splash:create
flutter_native_splash:
  background_image: "assets/images/splash.png"
  background_image_web: "assets/images/splash-web.png"

# rps unit, rps widget
scripts:
  gen-all: |
    $gen
    $l10n
  gen: dart run build_runner build --delete-conflicting-outputs
  get: dart pub get
  l10n: flutter gen-l10n
  unit: flutter test test/unit
  widget: flutter test test/widget
  reset:
    flutter clean
    flutter pub get
