// Mocks generated by Mockito 5.4.0 from annotations
// in currency_calc/test/unit/feature/currency/internal/domain/update/currency_visibility_updater_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i3;

import 'package:currency_calc/feature/currency/internal/domain/model/currency.dart'
    as _i6;
import 'package:currency_calc/feature/currency/internal/domain/repository/currency_repository.dart'
    as _i4;
import 'package:currency_calc/feature/currency/internal/domain/update/internal/selection/currency_selection_corrector.dart'
    as _i7;
import 'package:currency_calc/feature/setting/internal/domain/model/setting_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSettingModel_0 extends _i1.SmartFake implements _i2.SettingModel {
  _FakeSettingModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLocale_1 extends _i1.SmartFake implements _i3.Locale {
  _FakeLocale_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CurrencyRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCurrencyRepository extends _i1.Mock
    implements _i4.CurrencyRepository {
  @override
  _i5.Future<int> countVisibleSourceCurrencies() => (super.noSuchMethod(
        Invocation.method(
          #countVisibleSourceCurrencies,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
        returnValueForMissingStub: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);
  @override
  _i5.Future<int> countVisibleTargetCurrencies() => (super.noSuchMethod(
        Invocation.method(
          #countVisibleTargetCurrencies,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
        returnValueForMissingStub: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);
  @override
  _i5.Future<_i6.Currency?> loadByCode(String? code) => (super.noSuchMethod(
        Invocation.method(
          #loadByCode,
          [code],
        ),
        returnValue: _i5.Future<_i6.Currency?>.value(),
        returnValueForMissingStub: _i5.Future<_i6.Currency?>.value(),
      ) as _i5.Future<_i6.Currency?>);
  @override
  _i5.Future<List<_i6.Currency>> loadAllCurrencies() => (super.noSuchMethod(
        Invocation.method(
          #loadAllCurrencies,
          [],
        ),
        returnValue: _i5.Future<List<_i6.Currency>>.value(<_i6.Currency>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i6.Currency>>.value(<_i6.Currency>[]),
      ) as _i5.Future<List<_i6.Currency>>);
  @override
  _i5.Future<List<_i6.Currency>> loadCurrenciesByCodeFirstLetter(
          String? letter) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadCurrenciesByCodeFirstLetter,
          [letter],
        ),
        returnValue: _i5.Future<List<_i6.Currency>>.value(<_i6.Currency>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i6.Currency>>.value(<_i6.Currency>[]),
      ) as _i5.Future<List<_i6.Currency>>);
  @override
  _i5.Future<List<String>> loadCurrencyCodeFirstLetters() =>
      (super.noSuchMethod(
        Invocation.method(
          #loadCurrencyCodeFirstLetters,
          [],
        ),
        returnValue: _i5.Future<List<String>>.value(<String>[]),
        returnValueForMissingStub: _i5.Future<List<String>>.value(<String>[]),
      ) as _i5.Future<List<String>>);
  @override
  _i5.Future<Map<String, _i6.Currency>> loadAllIndexedByCode() =>
      (super.noSuchMethod(
        Invocation.method(
          #loadAllIndexedByCode,
          [],
        ),
        returnValue: _i5.Future<Map<String, _i6.Currency>>.value(
            <String, _i6.Currency>{}),
        returnValueForMissingStub: _i5.Future<Map<String, _i6.Currency>>.value(
            <String, _i6.Currency>{}),
      ) as _i5.Future<Map<String, _i6.Currency>>);
  @override
  _i5.Future<List<_i6.Currency>> loadVisibleSourceCurrencies() =>
      (super.noSuchMethod(
        Invocation.method(
          #loadVisibleSourceCurrencies,
          [],
        ),
        returnValue: _i5.Future<List<_i6.Currency>>.value(<_i6.Currency>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i6.Currency>>.value(<_i6.Currency>[]),
      ) as _i5.Future<List<_i6.Currency>>);
  @override
  _i5.Future<List<String>> loadVisibleSourceCurrencyCodes() =>
      (super.noSuchMethod(
        Invocation.method(
          #loadVisibleSourceCurrencyCodes,
          [],
        ),
        returnValue: _i5.Future<List<String>>.value(<String>[]),
        returnValueForMissingStub: _i5.Future<List<String>>.value(<String>[]),
      ) as _i5.Future<List<String>>);
  @override
  _i5.Future<List<_i6.Currency>> loadVisibleTargetCurrencies() =>
      (super.noSuchMethod(
        Invocation.method(
          #loadVisibleTargetCurrencies,
          [],
        ),
        returnValue: _i5.Future<List<_i6.Currency>>.value(<_i6.Currency>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i6.Currency>>.value(<_i6.Currency>[]),
      ) as _i5.Future<List<_i6.Currency>>);
  @override
  _i5.Future<List<String>> loadVisibleTargetCurrencyCodes() =>
      (super.noSuchMethod(
        Invocation.method(
          #loadVisibleTargetCurrencyCodes,
          [],
        ),
        returnValue: _i5.Future<List<String>>.value(<String>[]),
        returnValueForMissingStub: _i5.Future<List<String>>.value(<String>[]),
      ) as _i5.Future<List<String>>);
  @override
  _i5.Future<DateTime?> loadLastUpdateDate() => (super.noSuchMethod(
        Invocation.method(
          #loadLastUpdateDate,
          [],
        ),
        returnValue: _i5.Future<DateTime?>.value(),
        returnValueForMissingStub: _i5.Future<DateTime?>.value(),
      ) as _i5.Future<DateTime?>);
  @override
  _i5.Future<void> save(_i6.Currency? currency) => (super.noSuchMethod(
        Invocation.method(
          #save,
          [currency],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<void> saveAll(Map<String, _i6.Currency>? currencies) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveAll,
          [currencies],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<void> saveLastUpdateDateToNow() => (super.noSuchMethod(
        Invocation.method(
          #saveLastUpdateDateToNow,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [SettingModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingModel extends _i1.Mock implements _i2.SettingModel {
  @override
  String get languageCode => (super.noSuchMethod(
        Invocation.getter(#languageCode),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  String get fontFamily => (super.noSuchMethod(
        Invocation.getter(#fontFamily),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  String get themeType => (super.noSuchMethod(
        Invocation.getter(#themeType),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  String get selectedSourceCurrencyCode => (super.noSuchMethod(
        Invocation.getter(#selectedSourceCurrencyCode),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  String get selectedTargetCurrencyCode => (super.noSuchMethod(
        Invocation.getter(#selectedTargetCurrencyCode),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  List<String> get visibleSourceCurrencyCodes => (super.noSuchMethod(
        Invocation.getter(#visibleSourceCurrencyCodes),
        returnValue: <String>[],
        returnValueForMissingStub: <String>[],
      ) as List<String>);
  @override
  List<String> get visibleTargetCurrencyCodes => (super.noSuchMethod(
        Invocation.getter(#visibleTargetCurrencyCodes),
        returnValue: <String>[],
        returnValueForMissingStub: <String>[],
      ) as List<String>);
  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  _i5.Future<_i2.SettingModel> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i5.Future<_i2.SettingModel>.value(_FakeSettingModel_0(
          this,
          Invocation.method(
            #init,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.SettingModel>.value(_FakeSettingModel_0(
          this,
          Invocation.method(
            #init,
            [],
          ),
        )),
      ) as _i5.Future<_i2.SettingModel>);
  @override
  void updateLanguageCode(String? languageCode) => super.noSuchMethod(
        Invocation.method(
          #updateLanguageCode,
          [languageCode],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i3.Locale detectLocale() => (super.noSuchMethod(
        Invocation.method(
          #detectLocale,
          [],
        ),
        returnValue: _FakeLocale_1(
          this,
          Invocation.method(
            #detectLocale,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeLocale_1(
          this,
          Invocation.method(
            #detectLocale,
            [],
          ),
        ),
      ) as _i3.Locale);
  @override
  void updateFontFamily(String? fontFamily) => super.noSuchMethod(
        Invocation.method(
          #updateFontFamily,
          [fontFamily],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void updateThemeType(String? themeType) => super.noSuchMethod(
        Invocation.method(
          #updateThemeType,
          [themeType],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void updateSelectedSourceCurrencyCode(String? currencyCode) =>
      super.noSuchMethod(
        Invocation.method(
          #updateSelectedSourceCurrencyCode,
          [currencyCode],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void updateSelectedTargetCurrencyCode(String? currencyCode) =>
      super.noSuchMethod(
        Invocation.method(
          #updateSelectedTargetCurrencyCode,
          [currencyCode],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void updateVisibleSourceCurrencyCodes(List<String>? currencyCodes) =>
      super.noSuchMethod(
        Invocation.method(
          #updateVisibleSourceCurrencyCodes,
          [currencyCodes],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void updateVisibleTargetCurrencyCodes(List<String>? currencyCodes) =>
      super.noSuchMethod(
        Invocation.method(
          #updateVisibleTargetCurrencyCodes,
          [currencyCodes],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void addListener(_i3.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void removeListener(_i3.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [CurrencySelectionCorrector].
///
/// See the documentation for Mockito's code generation for more information.
class MockCurrencySelectionCorrector extends _i1.Mock
    implements _i7.CurrencySelectionCorrector {
  @override
  _i5.Future<void> correctSelectedSourceCurrency(
    _i6.Currency? currency,
    _i2.SettingModel? settingModel,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #correctSelectedSourceCurrency,
          [
            currency,
            settingModel,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<void> correctSelectedTargetCurrency(
    _i6.Currency? currency,
    _i2.SettingModel? settingModel,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #correctSelectedTargetCurrency,
          [
            currency,
            settingModel,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
