name: Verify code
on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
      - main
permissions: read-all
jobs:
    verify:
        name: Verify
        runs-on: ubuntu-latest
        steps:
        - name: Echo text
          run: echo "Hello, world!"

        - name: Clone flutter repository with master channel
        - uses: actions/checkout@v3
        - uses: subosito/flutter-action@v2
          with:
            channel: 'stable' # or: 'beta', 'dev' or 'master'
        - run: flutter --version
