name: Verify code
on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
      - main
permissions: read-all
jobs:
    verify:
        name: Verify
        runs-on: ubuntu-latest
        steps:
        - name: Clone flutter repository from stable channel
          uses: subosito/flutter-action@v2
          with:
            channel: 'stable' # or: 'beta', 'dev' or 'master'
        - run: flutter --disable-telemetry
        - run: flutter --version
