name: Verify code
on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
      - main
permissions:
  contents: read-all
jobs:
    verify:
        name: Verify
        runs-on: ubuntu-latest
        steps:
        - name: Echo text
          run: echo "Hello, world!"
