name: Verify code
on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
      - main
permissions: read-all
jobs:
    verify:
        name: Verify
        runs-on: ubuntu-latest
        steps:
        - name: Setup flutter
          uses: subosito/flutter-action@v2
          with:
            channel: 'stable' # or: 'beta', 'dev' or 'master'
        - run: flutter --disable-telemetry && flutter --version
        - run: flutter doctor -v
        - name: Checkout code
          uses: actions/checkout@v2
        - run: make get
        - run: make test
